# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OlympiadApp(object):
    def setupUi(self, OlympiadApp):
        OlympiadApp.setObjectName("OlympiadApp")
        OlympiadApp.resize(597, 445)
        self.centralwidget = QtWidgets.QWidget(OlympiadApp)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.subject_label = QtWidgets.QLabel(self.centralwidget)
        self.subject_label.setObjectName("subject_label")
        self.verticalLayout.addWidget(self.subject_label)
        self.subject_input = QtWidgets.QLineEdit(self.centralwidget)
        self.subject_input.setObjectName("subject_input")
        self.verticalLayout.addWidget(self.subject_input)
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setObjectName("name_input")
        self.verticalLayout.addWidget(self.name_input)
        self.date_label = QtWidgets.QLabel(self.centralwidget)
        self.date_label.setObjectName("date_label")
        self.verticalLayout.addWidget(self.date_label)
        self.date_input = QtWidgets.QLineEdit(self.centralwidget)
        self.date_input.setObjectName("date_input")
        self.verticalLayout.addWidget(self.date_input)
        self.level_label = QtWidgets.QLabel(self.centralwidget)
        self.level_label.setObjectName("level_label")
        self.verticalLayout.addWidget(self.level_label)
        self.level_input = QtWidgets.QLineEdit(self.centralwidget)
        self.level_input.setObjectName("level_input")
        self.verticalLayout.addWidget(self.level_input)
        self.add_button = QtWidgets.QPushButton(self.centralwidget)
        self.add_button.setObjectName("add_button")
        self.verticalLayout.addWidget(self.add_button)
        self.delete_button = QtWidgets.QPushButton(self.centralwidget)
        self.delete_button.setObjectName("delete_button")
        self.verticalLayout.addWidget(self.delete_button)
        self.table = QtWidgets.QTableWidget(self.centralwidget)
        self.table.setObjectName("table")
        self.table.setColumnCount(5)
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.table)
        self.sort_button = QtWidgets.QPushButton(self.centralwidget)
        self.sort_button.setObjectName("sort_button")
        self.verticalLayout.addWidget(self.sort_button)
        OlympiadApp.setCentralWidget(self.centralwidget)

        self.retranslateUi(OlympiadApp)
        QtCore.QMetaObject.connectSlotsByName(OlympiadApp)

    def retranslateUi(self, OlympiadApp):
        _translate = QtCore.QCoreApplication.translate
        OlympiadApp.setWindowTitle(_translate("OlympiadApp", "Olympiad Notes"))
        self.subject_label.setText(_translate("OlympiadApp", "Название предмета:"))
        self.name_label.setText(_translate("OlympiadApp", "Название олимпиады:"))
        self.date_label.setText(_translate("OlympiadApp", "Дата олимпиады (ДД.ММ.ГГГГ):"))
        self.level_label.setText(_translate("OlympiadApp", "Уровень олимпиады:"))
        self.add_button.setText(_translate("OlympiadApp", "Добавить олимпиаду"))
        self.delete_button.setText(_translate("OlympiadApp", "Удалить выбранную олимпиаду"))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("OlympiadApp", "id:"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("OlympiadApp", "Предмет:"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("OlympiadApp", "Олимпиада:"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("OlympiadApp", "Дата:"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("OlympiadApp", "Уровень РСОШ:"))
        self.sort_button.setText(_translate("OlympiadApp", "Сортировать"))
